services:
  postgres:
    image: "postgres:15.2-alpine"
    restart: always
    container_name: sinau-db
    environment:
      POSTGRES_USER: sinau
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
